---
title: "bm_finalproject"
author: "Coco"
date: "12/7/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(multcomp)
library(faraway) 
library(ggplot2)
library(patchwork)
library("leaps")
library(caret)
library(dplyr)
library(glmnet)
library(patchwork)
library(broom)
library(olsrr)
```

##Read data

```{r include = FALSE}
 cancer_df <- read.csv(file = "./data/Cancer_Registry.csv") %>% 
   janitor::clean_names() %>% 
   separate(geography, into = c("county", "state"),sep = ",") %>% 
   separate(binned_inc, into = c("binned_inc_low","binned_inc_high"), sep = ",") %>% 
   mutate(binned_inc_low = str_replace(binned_inc_low,"[(]",""),
          binned_inc_high = str_replace(binned_inc_high,"[]]",""),
          binned_inc_low = as.numeric(gsub(",","",binned_inc_low,fixed=TRUE)),
          binned_inc_high = as.numeric(gsub(",","",binned_inc_high,fixed=TRUE)),
          median_inc = (binned_inc_high+binned_inc_low)/2,
          pct_no_cov = 100 - pct_public_coverage_alone - pct_private_coverage_alone,
          black_high_ind = case_when(pct_black > 9 ~ "1", TRUE ~ "0"),
          black_high_ind = as.numeric(black_high_ind)) %>% 
  dplyr::select(-binned_inc_high, -binned_inc_low, -contains("coverage"),-pct_no_hs18_24, -pct_hs18_24, -pct_some_col18_24,-pct_hs25_over,-pct_married_households)


num_df <- cancer_df %>% 
  dplyr::select(-county, -state, -median_age_male, -median_age_female,-pct_white,-pct_black,-pct_asian,-pct_other_race) %>% 
  na.omit()
  
```

## Exploratory Analysis

```{r}
cor(num_df) %>% knitr::kable()

bach = num_df %>% 
  ggplot(aes(x = target_death_rate, y  = pct_bach_deg25_over)) + 
  geom_point()

inc = num_df %>% 
  ggplot(aes(x = target_death_rate, y  = incidence_rate)) + 
  geom_point()

income = num_df %>% 
  ggplot(aes(x = target_death_rate, y  = med_income)) + 
  geom_point()

employ = num_df %>% 
  ggplot(aes(x = target_death_rate, y  = pct_employed16_over)) + 
  geom_point()

(bach + inc) / (income + employ)
```



##stepwise 

```{r results=FALSE}
full_model = lm(target_death_rate ~ ., data = num_df)
summary(full_model)

step_model <- stepAIC(full_model, direction = "both", 
                      trace = FALSE)
summary(step_model)
vif(step_model)
step_model<- update(step_model,.~.-avg_deaths_per_year)
step_model_ours<- update(step_model,.~.-pop_est2015)
step_model_plus<- update(step_model_ours,.~.+black_high_ind*incidence_rate)
step_model_plus<- update(step_model_plus,.~.+pct_no_cov)
```

```{r}
summary(step_model_ours)
summary(step_model_plus)
vif(step_model)
vif(step_model_plus)
```

###Cp&AIC&adjustedr2

```{r}

ours = glance(step_model_ours) %>% 
  as.data.frame() %>% 
  dplyr::select(adj.r.squared, sigma, AIC, BIC, p.value) %>% 
  mutate(cp = ols_mallows_cp(step_model_ours, full_model)) %>% 
  rename(RSE = sigma)

ours %>%  
  knitr::kable(digits = 2)

plus = glance(step_model_plus) %>% 
  as.data.frame() %>% 
  dplyr::select(adj.r.squared, sigma, AIC, BIC, p.value) %>% 
  mutate(cp = ols_mallows_cp(step_model_plus, full_model)) %>% 
  rename(RSE = sigma)
  
plus %>%  
  knitr::kable(digits = 2)
```

We decide to use plus as the final model


##Backward elimination 
```{r results = FALSE}

back_model <- step(full_model, direction = "backward", trace=FALSE ) 
summary(back_model)
vif(back_model)

```

backward elimination suggest the same with stepwise


##Forward elimination

```{r results = FALSE}
null<- lm(target_death_rate ~ 1, data = num_df)
for_model <- step(null, scope=list(lower=null, upper=full_model), direction="forward")
summary(for_model)
vif(for_model)
for_model<- update(for_model,.~.-avg_deaths_per_year)
for_model<- update(for_model,.~.-pop_est2015)
for_model<- update(for_model,.~.+black_high_ind*incidence_rate)

```

```{r}
summary(for_model)
vif(for_model)
```


https://www.cancer.org/latest-news/facts-and-figures-2018-rate-of-deaths-from-cancer-continues-decline.html

### Lasso Regression
```{r}
# Try a grid of values for lambda: from 10^-2 to 10^5

grid <- 10^seq(5,-2, length=100)

Y <- num_df[,3]

X <- 
  model.matrix(target_death_rate ~ avg_ann_count + incidence_rate + poverty_percent + percent_married + pct_bach_deg25_over + pct_unemployed16_over + birth_rate + black_high_ind + incidence_rate*black_high_ind , data = num_df)

set.seed(1)

train<-sample(1:nrow(X),nrow(X)/2)

test<-(-train)

Y.test<-Y[test]



lasso1<- glmnet(X[train ,],Y[train], alpha =1, lambda =grid)

# Cross-validation
set.seed(2)
cv.out<-cv.glmnet(X[train,],Y[train])
plot(cv.out)
# Fit a Lasso model with all observations with the best lambda

best.lambda<-cv.out$lambda.min

lasso2<- glmnet(X[train ,],Y[train], alpha =1, lambda=best.lambda)
lasso.cv<- cv.glmnet(X[train ,],Y[train], alpha = 1)
coef(lasso.cv)

summary(lasso2)
```

## Outliers Using Studentized Residuals 
```{r}
stu_res_step = rstandard(step_model)
outliers_y_step = stu_res_step[abs(stu_res_step) > 2.5]
outliers_y_step

# 282, 1221, 1366
```

## Cook's Distance 
```{r}
# step model
plot(step_model)

# backward model
plot(back_model)


# Observation 282, 1221, 1366 should be looked at 
```

## Various Measures of Influence
```{r}
influence.measures(step_model)
summary(step_model)

# 282, 1221, 1336 noted as potentially influential 

plot(num_df$incidence_rate, num_df$target_death_rate)
```



## Remove Outliers
```{r}
# remove observation 282 only
num_df_no_282 = cancer_df %>% 
  dplyr::select(-county, -state, -median_age_male, -median_age_female,-pct_white,-pct_black,-pct_asian,-pct_other_race) %>% 
  tibble::rowid_to_column() %>% 
  filter(rowid != 282) %>% 
  na.omit()

step_no_282 = update(step_model, . ~ ., data = num_df_no_282)
summary(step_no_282)

back_no_282 = update(back_model, . ~ ., data = num_df_no_282)
summary(back_no_282)

# remove observations 282, 1221, 1366
num_df_no_282_1221_1366 = cancer_df %>% 
  dplyr::select(-county, -state, -median_age_male, -median_age_female,-pct_white,-pct_black,-pct_asian,-pct_other_race) %>% 
  tibble::rowid_to_column() %>% 
  filter(rowid != 282 & rowid != 1221 & rowid != 1366) %>% 
  na.omit()

step_no282_1221_1366 = update(step_model, . ~ ., data = num_df_no_282_1221_1366)
summary(step_no282_1221_1366)

back_no282_1221_1366 = update(back_model, . ~ ., data = num_df_no_282_1221_1366)
summary(back_no282_1221_1366)
```

